revert t3_regressions to trunk version

diff --git a/t3_regressions b/t3_regressions
--- a/t3_regressions
+++ b/t3_regressions
@@ -1,26 +1,30 @@
-#!/bin/bash
+#!/bin/bash -x
 
 RUN_TESTS='yes'
 OUT_FILE=''
-while getopts 'shof:' opt; do
+while getopts 'sho:i:' opt; do
     case $opt in
-        s) RUN_TESTS='no' ;;
-        o) OUT_FILE=$OPTARG ;;
-        f) IN_FILE=$OPTARG ;;
-        ?) echo 'Run with -s to skip "mvn test", -o <file> to output the failures to a file' ; exit 1 ;;
+        s) RUN_TESTS='no' ;; # whether to run $(mvn test...) or assume it's already been run
+        o) OUT_FILE=$OPTARG ;; # if provided, the file to output failures to
+        i) INPUT_FAILURES=$OPTARG ;; # if provided, the file to read previous known failures from (instead of wget'ing from nighthawk)
+        ?) echo "read the script's source to find the options :)" ; exit 1 ;;
     esac
 done
 
-if [ -z "$IN_FILE" ] ; then 
-	echo "Getting known failures from nighthawk."
-	KNOWN_FAILURES=$(wget -qO - http://172.16.20.117/t3-regressions/known-failures)
-	if [ -n "$OUT_FILE" ]; then
-    	echo "...outputting to $OUT_FILE"
-    	echo "$KNOWN_FAILURES" > $OUT_FILE
-	fi
+if [ -n "$INPUT_FAILURES" ]; then
+    if [ ! -e $INPUT_FAILURES ]; then
+        echo "Input file $INPUT_FAILURES not found"
+        exit 1
+    fi
+    echo "Getting known failures from provided file: $INPUT_FAILURES"
+    KNOWN_FAILURES=$(cat $INPUT_FAILURES)
 else
-	echo "reading from local source"
-	KNOWN_FAILURES=$(cat $IN_FILE)
+    echo "Getting known failures from nighthawk."
+    KNOWN_FAILURES=$(wget -qO - http://172.16.20.117/t3-regressions/known-failures)
+fi
+if [ -n "$OUT_FILE" ] && [ "$OUT_FILE" != "$INPUT_FAILURES" ]; then
+    echo "...outputting to $OUT_FILE"
+    echo "$KNOWN_FAILURES" > $OUT_FILE
 fi
 
 if [ "$RUN_TESTS" = "yes" ]; then
@@ -34,8 +38,10 @@ else
 fi
 
 BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-FAILED=$(grep '^testYaml' $BASE/target/surefire-reports/com.akiban.sql.pg.PostgresServerMiscYamlIT.txt | sed -E 's/testYaml \[([^]]*).*/\1/' | sort)
-FAILDIFF=$(diff --suppress-common-lines <(echo "$KNOWN_FAILURES") <(echo "$FAILED"))
+# the sed of '-' -> 'ZZZ' -> '-' is to ensure stable sorting across OSes
+FAILED=$(grep '^testYaml' $BASE/target/surefire-reports/com.akiban.sql.pg.PostgresServerMiscYamlIT.txt | sed -E 's/testYaml \[([^]]*).*/\1/' | sed 's/-/ZZZ/g' | sort | sed 's/ZZZ/-/g')
+FAILDIFF=$(echo "$FAILED" | diff <(echo "$KNOWN_FAILURES") <(echo "$FAILED"))
+echo "$FAILDIFF"
 REGRESSIONS=$(echo "$FAILDIFF" | grep '>')
 FIXES=$(echo "$FAILDIFF" | grep '<')
 RESULT="neither"
@@ -55,7 +61,6 @@ fi
 echo "Fixes:       $FIXES_COUNT"
 echo "Regressions: $REGRESSIONS_COUNT"
 
-EXIT_CODE=1
 if [ "$RESULT" = "fixes" ] && [ -n "$OUT_FILE" ]; then
     if [ -n "$FAILED" ]; then
         echo "Updating expected failures file with $(echo "$FAILED" | wc -l) failures"
@@ -64,7 +69,6 @@ if [ "$RESULT" = "fixes" ] && [ -n "$OUT_FILE" ]; then
     fi
     echo "$FAILED" > $OUT_FILE
 elif [ "$RESULT" = "neither" ]; then
-    EXIT_CODE=0
     echo "No fixes or regressions."
 fi
-exit $EXIT_CODE
+exit $(test "$REGRESSIONS_COUNT" = "0")
