moving the regressions checker to teh cloud!

diff --git a/t3_regressions b/t3_regressions
--- a/t3_regressions
+++ b/t3_regressions
@@ -1,12 +1,20 @@
 #!/bin/bash
 
 RUN_TESTS='yes'
-while getopts 'sh' opt; do
+OUT_FILE=''
+while getopts 'sho:' opt; do
     case $opt in
         s) RUN_TESTS='no' ;;
-        ?) echo 'Run with -s to skip "mvn test", or else with no args' ; exit 1 ;;
+        o) OUT_FILE=$OPTARG ;;
+        ?) echo 'Run with -s to skip "mvn test", -o <file> to output the failures to a file' ; exit 1 ;;
     esac
 done
+
+echo "Getting known failures from nighthawk."
+KNOWN_FAILURES=$(wget -qO - http://172.16.20.117/t3-regressions/known-failures)
+if [ -n "$OUT_FILE" ]; then
+    echo "$KNOWN_FAILURES" > $OUT_FILE
+fi
 
 if [ "$RUN_TESTS" = "yes" ]; then
     CMD='mvn test -Dtest=PostgresServerMiscYamlIT -Dakiban.test.extraJvmArgs=-Dnewtypes=true'
@@ -19,9 +27,8 @@ else
 fi
 
 BASE=$(dirname $(readlink -f $0))
-FAILURES_FILE=$BASE/src/test/resources/com/akiban/sql/pg/yaml/newtypes-failures
 FAILED=$(grep '^testYaml' $BASE/target/surefire-reports/com.akiban.sql.pg.PostgresServerMiscYamlIT.txt | sed -r 's/testYaml \[([^]]*).*/\1/' | sort)
-FAILDIFF=$(echo "$FAILED" | diff --suppress-common-lines $FAILURES_FILE -)
+FAILDIFF=$(diff --suppress-common-lines <(echo "$KNOWN_FAILURES") <(echo "$FAILED"))
 REGRESSIONS=$(echo "$FAILDIFF" | grep '>')
 FIXES=$(echo "$FAILDIFF" | grep '<')
 RESULT="neither"
@@ -37,7 +44,6 @@ fi
 EXIT_CODE=1
 if [ "$RESULT" = "fixes" ]; then
     echo "Updating expected failures file"
-    echo "$FAILED" > $FAILURES_FILE
 elif [ "$RESULT" = "neither" ]; then
     EXIT_CODE=0
     echo "No fixes or regressions."
