Update redhat init script to be more informative when non-zero exit code is returned from the status function.

diff --git a/redhat/akiban-server b/redhat/akiban-server
--- a/redhat/akiban-server
+++ b/redhat/akiban-server
@@ -82,9 +82,22 @@ case "$1" in
         ;;
     stop)
         status -p $pid_file akiban > /dev/null 2>&1
-        if [ $? -ne 0 ]; then
-            log_failure_msg "Shutdown Akiban"
-            exit 1
+        retval=$?
+        if [ ${retval} -ne 0 ]; then
+            # return codes from status as documented in LSB spec
+            # http://refspecs.linuxbase.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+            case ${retval} in
+            1) 
+              log_failure_msg "Akiban is not running, but PID file exists"
+              ;;
+            3) 
+              log_failure_msg "Akiban process is not running"
+              ;;
+            *)
+              log_failure_msg "Shutdown Akiban"
+              ;;
+            esac
+            exit ${retval}
         fi
         echo -n "Shutdown Akiban "
         su $AKIBAN_OWNR -c "kill `cat $pid_file`"
